name: Build and Release Game
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      shell: bash
      run: |
        if [[ ${{ matrix.os }} == 'windows-latest' ]]; then
          choco upgrade -y --accept-license meson sdl2 sdl2_ttf ninja
        elif [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
          sudo apt-get install -y meson ninja-build libsdl2-dev libsdl2-ttf-dev
        elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
          brew install meson ninja sdl2 sdl2_ttf
        fi
    - name: Set up Meson and Ninja
      run: |
        meson setup --buildtype=release build
    - name: Build game
      run: meson compile -C build
    - name: Package dist
      run: |
        mkdir -p dist/
        cp -r build/stax resources/ dist/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}
        path: dist/

